{{- if .Values.logReadApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabee-pi-agent.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "fabee-pi-agent.name" . }}
  ports:
    - name: log-read-api
      port: {{ .Values.logReadApi.port }}
      targetPort: log-read-api
      protocol: TCP
{{- end }}
